### PR TITLE
Update README to reflect latest taskgraph changes

### PR DESCRIPTION
**Pull request by phargogh**
This PR updates the taskgraph README to reflect the latest API changes and also reflect the requirement of `if __name__ == '__main__':`.

### CODE REVIEW

**Review by emlys — DISMISSED** [review]
Thanks @phargogh! This works for me. Just one suggestion would be to add `logging.basicConfig(level=logging.DEBUG)` at the top because right now if you run this example, you just see the `EOFError`. It could be nice to show the extra info so it's clearer that it is actually working. But also it's just an example for us and doesn't really matter, so I leave it up to you :)

**Comment by phargogh** [comment]
@emlys added in cc17398.  Back to you!

**Comment by richpsharp** [comment]
FYI, I linked #43 here just in case that's what this PR is for.

**Comment by phargogh** [comment]
@emlys I just resolved the merge conflict on `HISTORY.rst`, so I think this PR is ready to go

**Review by emlys — APPROVED** [review]
whoops sorry, I totally forgot about this one!

**Pull request merged**
